db1:
  restart: always
  environment:
    MONGO_ROLE: primary
  tty: true
  hostname: db1
  image: benpiper/mongo-rep-set:latest
  links:
  - db2:db2
  - db3:db3
  stdin_open: true

db2:
  restart: always
  tty: true
  hostname: db2
  image: benpiper/mongo-rep-set:latest
  links:
  - db1:db1
  - db3:db3
  stdin_open: true

db3:
  restart: always
  tty: true
  hostname: db3
  image: benpiper/mongo-rep-set:latest
  links:
  - db1:db1
  - db2:db2
  stdin_open: true
